name: Deploy Vite Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build Vite App and Deploy via Nginx
    runs-on: self-hosted # Use self-hosted runner instead of GitHub-hosted runners

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          clean: false

      # Install dependencies
      - name: Take existing compose down
        run: docker compose -f ./compose.yaml -p rembg down
        continue-on-error: true

      # Build the Vite application
      - name: Take the compose up
        run: docker compose -f ./compose.yaml -p rembg up -d --build
