name: Deploy Vite Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build Vite App and Deploy via Nginx
    runs-on: self-hosted # Use self-hosted runner instead of GitHub-hosted runners

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          clean: false

      # Install dependencies
      - name: Install dependencies
        run: |
          pnpm install
        working-directory: ./client

      # Build the Vite application
      - name: Build Vite App
        run: |
          pnpm run build
        working-directory: ./client

      # Copy the dist directory to the target server location
      - name: Copy dist directory to /www/rembg.snabajja.in
        run: |
          cp -r ./client/dist/* /www/rembg.snabajja.in/
        working-directory: ./client

      # Restart Nginx (if necessary)
      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
